'use strict';

// 错误代码
export default {
    // 不能踢出管理员
    CANNOT_KICK_OUT_MANAGER: "MERCHANT.CANNOT_KICK_OUT_MANAGER",

    // 当前用户未绑定商家
    CURRENT_USER_UNBOUNDED_MERCHANTS: "MERCHANT.CURRENT_USER_UNBOUNDED_MERCHANTS",

    // 商家店名重复
    DUPLICATE_MERCHANT_NAME: "MERCHANT.DUPLICATE_MERCHANT_NAME",

    // 用户不存在
    NO_SUCH_USER: "MERCHANT.NO_SUCH_USER",

    // 资源不隶属该商家
    RESOURCE_NOT_BELONG_TO_CURRENT_MERCHANT: "MERCHANT.RESOURCE_NOT_BELONG_TO_CURRENT_MERCHANT",

    // 用户已经绑定了商家
    USER_IS_BOUND: "MERCHANT.USER_IS_BOUND"
};
