'use strict';

// 错误代码
export default {
    // 名称重复
    DUPLICATE_USER_NAME: "USER.DUPLICATE_USER_NAME",

    // 授权人没有相应的权限
    GRANTER_NO_THESE_PERMISSIONS: "USER.GRANTER_NO_THESE_PERMISSIONS",

    // 密码不正确
    INCORRECT_PASSWORD: "USER.INCORRECT_PASSWORD",

    // 用户类型无效
    INVALID_USER_KIND: "USER.INVALID_USER_KIND",

    // 用户不存在
    NO_SUCH_USER: "USER.NO_SUCH_USER",

    // 用户没有权限操作资源
    PERMISSION_DENIED: "USER.PERMISSION_DENIED",

    // 资源不隶属该用户
    RESOURCE_NOT_BELONG_TO_CURRENT_USER: "USER.RESOURCE_NOT_BELONG_TO_CURRENT_USER",

    // 用户未登录
    USER_NOT_LOGGED_IN: "USER.USER_NOT_LOGGED_IN",

    // 微信授权重定向
    WECHAT_AUTH_REDIRECT: "USER.WECHAT_AUTH_REDIRECT"
};
